# Hand-curated entries. Every entry's details were read on source_url (and alt_sources).
# Fields not shown on the source are left empty.
OTR="https://www.ontheroute.co.za/your-garden-route-event-guide-1-october/"
MB="https://visitmosselbay.co.za/event/"
M=[]
def add(**k): M.append(k)

# ---------------- Garden Route / Mossel Bay / Oudtshoorn ----------------
add(title="Wilderness Arts Festival",category="festival",start_date="2026-10-08",end_date="2026-10-11",time="09:00-17:00",town="Wilderness",venue="Fairy Knowe Hotel & venues across the village",venue_address="1 Dumbleton Road, Wilderness",price_from="",ticket_url="",source_url=OTR,source_name="On The Route (Garden Route event guide)",alt_sources=["https://www.wildernessartfestival.co.za/"],notes="Visual art, music, performance and literature; open to the public.")
add(title="Hemelruim – desert disco open-air concert (Spoegwolf, Tasché, Noemwoord)",category="concert",start_date="2026-10-10",time="Gates 17:00, music 18:00",town="Oudtshoorn",venue="Oudtshoorn Sports Grounds (REC)",price_from="R295",ticket_url="",source_url=OTR,source_name="On The Route (Garden Route event guide)",alt_sources=["https://www.diehoorn.com/nuus/hemelruim-bring-woestyn-disko/"],notes="Tickets at Computicket, Checkers, Shoprite, Usave; cheaper in advance. Klein Karoo, listed in Garden Route guide.")
add(title="Knysna RnB, Soul and Afro-Pop 2026",category="festival",start_date="2026-10-10",time="10:00-22:00",town="Knysna",venue="Loerie Park",venue_address="",price_from="R150",ticket_url="",source_url="https://www.toodoo.co.za/knysna-rnb-soul-and-afro-pop-2026/",source_name="toodoo.co.za",alt_sources=[],notes="Full-day R&B/soul/Afro-pop festival; tickets via Computicket per listing.")
add(title="RE/MAX 10th Garden Route Kite Festival",category="festival",start_date="2026-10-18",time="09:30",town="Sedgefield",venue="Scarab Village",venue_address="",price_from="",ticket_url="",source_url="https://www.visitknysna.co.za/whats-on/events/garden-route-kite-festival-3/",source_name="Visit Knysna",alt_sources=[OTR,"https://www.toodoo.co.za/garden-route-kite-festival-2026/"],notes="International kite flyers, family day.")
add(title="Magnificent Movie Music – Carpe Musicam! Concert Orchestra & Choir",category="concert",start_date="2026-10-11",time="15:30-19:00",town="Mossel Bay",venue="Dias Museum",venue_address="1 Market Street, Mossel Bay",price_from="",ticket_url="https://paystack.com/buy/11oct-mmm",source_url=MB+"magnificent-movie-music/",source_name="Visit Mossel Bay (tourism calendar)",alt_sources=[],notes="Film scores performed live (the Sedgefield show on 4 Oct was R180).")
for d in ["2026-10-10","2026-10-17","2026-10-24","2026-10-31"]:
    add(title="Misty Valley Octoberfest",category="festival",start_date=d,time="09:00",town="Mossel Bay",venue="Misty Valley Farm",venue_address="Misty Valley Farm, Brandwacht, Mossel Bay",price_from="Free entry",ticket_url="",source_url=MB+"misty-valley-octoberfest/"+d+"/",source_name="Visit Mossel Bay (tourism calendar)",alt_sources=[OTR],notes="Craft beer, food, live music; runs on Saturdays in October.")
add(title="Louvain Burn Music & Arts Festival",category="festival",start_date="2026-11-06",end_date="2026-11-09",time="",town="Oudtshoorn",venue="Louvain Guest Farm",price_from="R1380",ticket_url="https://louvainburnkaroo.com/buytickets/",source_url="https://louvainburnkaroo.com/buytickets/",source_name="Louvain Burn (official site)",alt_sources=[OTR],notes="Camping festival; full passes incl. 3 nights camping (Round 2 price). No day passes.")
add(title="Leisure Isle Festival 2026",category="festival",start_date="2026-11-07",end_date="2026-11-08",time="Sat 09:00-17:00, Sun 10:00-15:00",town="Knysna",venue="Leisure Isle",venue_address="",price_from="",ticket_url="",source_url="https://www.visitknysna.co.za/whats-on/events/2026-leisure-isle-festival/",source_name="Visit Knysna",alt_sources=[OTR,"https://www.leisureisleknysna.co.za/the-leisure-isle-festival/"],notes="21st charity festival: stalls, food, family fun, fun run/walk.")
add(title="Eden Fest 2026",category="festival",start_date="2026-11-07",time="08:00-19:00",town="Mossel Bay",venue="Die Gat",venue_address="Mayixhale Street, KwaNonqaba, Mossel Bay",price_from="",ticket_url="",source_url=MB+"eden-fest-2026/",source_name="Visit Mossel Bay (tourism calendar)",alt_sources=[],notes="Music, sport, vehicles and food festival.")
add(title="MosJazz 2026",category="festival",start_date="2026-11-26",end_date="2026-11-29",time="All day",town="Mossel Bay",venue="Santos Beach (De Bakke Santos Beach Resort)",venue_address="Santos Beach, Mossel Bay",price_from="",ticket_url="",source_url=MB+"mosjazz-2026/",source_name="Visit Mossel Bay (tourism calendar)",alt_sources=[OTR],notes="11th year: jazz, Afrobeat, soul and R&B on the beachfront.")
add(title="Plett Rage 2026",category="festival",start_date="2026-11-27",end_date="2026-12-03",time="",town="Plettenberg Bay",venue="Plettenberg Bay Main Beach",price_from="R1900",ticket_url="https://plettrage.howler.co.za/plettrage26",source_url="https://plettrage.howler.co.za/plettrage26",source_name="Howler",alt_sources=["https://www.plett-tourism.co.za/events/plett-rage-2026/",OTR],notes="School-leavers' festival.")
add(title="Matriekbaai 2026",category="festival",start_date="2026-11-27",end_date="2026-12-05",time="",town="Mossel Bay",venue="Diaz Hotel and Resort",venue_address="1 Beach East Blvd, Die Voor Bay, Mossel Bay",price_from="Free (registration)",ticket_url="https://www.howler.co.za/matriekbaai2026",source_url=MB+"matriekbaai-2026/",source_name="Visit Mossel Bay (tourism calendar)",alt_sources=["https://www.howler.co.za/matriekbaai2026",OTR],notes="School-leavers' festival, ages 18-22.")
add(title="AmfiHart 2026 (incl. Spoegwolf)",category="festival",start_date="2026-12-04",end_date="2026-12-05",time="",town="Hartenbos",venue="ATKV Hartenbos Amphitheatre",venue_address="169 Majuba Avenue, Hartenbos",price_from="R175",ticket_url="https://www.howler.co.za/AmfiHart26",source_url="https://www.howler.co.za/AmfiHart26",source_name="Howler",alt_sources=[MB+"amfihart-2026/",OTR],notes="5th AmfiHart: artists over 4-5 Dec, funfair, food stalls, market.")
add(title="Garden Route Rare Plant Festival",category="festival",start_date="2026-12-12",end_date="2026-12-13",time="",town="George",venue="Garden Route Botanical Garden",venue_address="",price_from="",ticket_url="",source_url=OTR,source_name="On The Route (Garden Route event guide)",alt_sources=[],notes="Third annual gathering for collectors of rare plants (not a music event).")
add(title="Float Fest SA – Groot Brak 2026",category="festival",start_date="2026-12-18",time="09:00-20:00",town="Groot Brak",venue="Suiderkruis Beach picnic area",venue_address="Suiderkruis Beach, Great Brak River",price_from="R250",ticket_url="https://weticket.co.za/event/details/1000189-float-fest-groot-brak",source_url=MB+"float-festival-grootbrak/",source_name="Visit Mossel Bay (tourism calendar)",alt_sources=["https://www.toodoo.co.za/float-fest-groot-brak-2026/",OTR],notes="River floating, live music and DJs. Price per adult as listed on toodoo.")
add(title="Hartenbos GrootFees: AiG-Buitelug",category="festival",start_date="2026-12-19",time="19:00-23:00 (gates 17:00)",town="Hartenbos",venue="ATKV Hartenbos Amphitheatre",venue_address="169 Majuba Avenue, Hartenbos",price_from="R295",ticket_url="https://itickets.co.za/events/486560",source_url="https://itickets.co.za/events/486560",source_name="iTickets",alt_sources=[MB+"aig-buitelug-hartenbos-grootfees/","https://afrmusieknuus.co.za/2026/08/27/betify-hartenbos-grootfees-2026-nog-groter-die-jaar/"],notes="Demi Lee Moore, Ruhan du Toit, Ricus Nel, Jo Black, Refentse, Barto, Juanita du Plessis, JACOBUS, Juan Boucher. Kids under 13 R150.")
add(title="Hartenbos GrootFees: Alternatief is Groot",category="festival",start_date="2026-12-29",time="16:00",town="Hartenbos",venue="ATKV Hartenbos Amphitheatre",venue_address="169 Majuba Avenue, Hartenbos",price_from="R295",ticket_url="",source_url=MB+"alternatief-is-groot-hartenbos-groot-fees/",source_name="Visit Mossel Bay (tourism calendar)",alt_sources=["https://afrmusieknuus.co.za/2026/08/27/betify-hartenbos-grootfees-2026-nog-groter-die-jaar/"],notes="JACOBUS, ONS, Die Heuwels Fantasties, Francois van Coke, Spoegwolf, Droomsindroom, G-String. Price per afrmusieknuus (general access).")
add(title="Hartenbos GrootFees: GrootJol (New Year's Eve)",category="festival",start_date="2026-12-31",time="19:00-23:00 (gates 17:00)",town="Hartenbos",venue="ATKV Hartenbos Amphitheatre",venue_address="169 Majuba Avenue, Hartenbos",price_from="R295",ticket_url="https://itickets.co.za/register/new/486562",source_url="https://itickets.co.za/register/new/486562",source_name="iTickets",alt_sources=[MB+"groot-jol-hartenbos-groot-fees/","https://afrmusieknuus.co.za/2026/08/27/betify-hartenbos-grootfees-2026-nog-groter-die-jaar/"],notes="Brendan Peyper, Robbie Wessels, Appel, Bernice West, Monique Steyn, Liezel Pieters, Danny Smoke, Chris Steyn.")
add(title="Punt in die Wind Kunste-Week (arts festival)",category="festival",start_date="2026-12-19",end_date="2026-12-26",time="",town="Mossel Bay",venue="Mossel Bay Stadsaal (Town Hall)",venue_address="Mossel Bay Town Hall, Mossel Bay",price_from="",ticket_url="https://itickets.co.za/events/486614",source_url="https://itickets.co.za/events/486614",source_name="iTickets",alt_sources=[],notes="Multi-day access; Afrikaans music, theatre and kids' shows.")
for iid,title,d,t in [("486591x","",None,None)]: pass
for iid,title,d,t in [("486199","Steve Hofmeyr – Punt in die Wind","2026-12-20","20:00"),("486200","Marion Holm – Punt in die Wind","2026-12-21","10:00"),("486592","Bobby van Jaarsveld – Punt in die Wind","2026-12-23","20:00"),("486213","Magda & Erhard Louw – Punt in die Wind","2026-12-24","13:00"),("486215","Klipwerf (langarm dance) – Punt in die Wind","2026-12-26","20:00")]:
    add(title=title,category="concert",start_date=d,time=t,town="Mossel Bay",venue="Mossel Bay Stadsaal (Town Hall)",venue_address="Mossel Bay Town Hall, Mossel Bay",price_from="",ticket_url="https://itickets.co.za/events/"+iid,source_url="https://itickets.co.za/events/"+iid,source_name="iTickets",alt_sources=[],notes="Part of Punt in die Wind Kunste-Week.")
# ReedValley concerts (Visit Mossel Bay calendar)
RV=dict(town="Mossel Bay",venue="ReedValley",venue_address="ReedValley Farm, R327, Mossel Bay",source_name="Visit Mossel Bay (tourism calendar)",ticket_url="",alt_sources=[])
for slug,title,d,price in [("jo-black-live-at-reedvalley","Jo Black Live at ReedValley","2026-10-10","R220"),("the-rivertones-at-reedvalley","The Rivertones at ReedValley","2026-10-30","R250"),("jakkie-louw-live-at-reedvalley","Jakkie Louw Live at ReedValley","2026-11-07",""),("dozi-live","Dozi Live at ReedValley","2026-11-13",""),("christia-visser-live","Christia Visser Live at ReedValley","2026-11-14",""),("amy-winehouse-tribute-at-reedvalley","Amy Winehouse Tribute at ReedValley","2026-11-27","R200"),("see-sand-live","See & Sand Live at ReedValley","2026-12-14",""),("chera-lee-live","Chera Lee Live at ReedValley","2026-12-15",""),("ballyhoo-live","Ballyhoo Live at ReedValley","2026-12-17",""),("mathys-roets-live-at-reedvalley","Mathys Roets Live at ReedValley","2026-12-19","R250"),("refentse-live-at-reedvalley","Refentse Live at ReedValley","2026-12-20","R295"),("roan-ash-live-at-reedvalley","Roan Ash Live at ReedValley","2026-12-21","R350"),("tribute-to-elvis-at-reedvalley","Tribute to Elvis Presley (James Marais & Monique Cassells) at ReedValley","2026-12-22","R200"),("joshua-na-die-reen-live-at-reedvalley","Joshua na die Reën Live at ReedValley","2026-12-23","R270"),("jaun-boucher-live-at-reedvalley","Juan Boucher Live at ReedValley","2026-12-26","R350"),("glaskas-live-at-reedvalley","Glaskas Live at ReedValley","2026-12-28","R280"),("masters-of-rock-mark-haze-group","Masters of Rock – Mark Haze & Group (NYE) at ReedValley","2026-12-31","R450"),("tribute-to-neil-diamond-at-reedvalley-2","Tribute to Neil Diamond at ReedValley","2027-01-04","R300"),("tribute-to-neil-diamond-at-reedvalley-3","Tribute to Neil Diamond at ReedValley","2027-01-05","R300")]:
    add(title=title,category="concert",start_date=d,time="20:00",price_from=price,source_url=MB+slug+"/",notes="",**RV)
# Howler – Garden Route
H="Howler"
add(title="Get Lucky Summer (Beacon Isle) Plett – Matthew Mole & friends (Edition 1)",category="concert",start_date="2026-12-20",time="",town="Plettenberg Bay",venue="Beacon Isle Resort",venue_address="Beacon Island Crescent, Plettenberg Bay",price_from="R180",ticket_url="https://www.howler.co.za/GLSBI1",source_url="https://www.howler.co.za/GLSBI1",source_name=H,alt_sources=[],notes="")
add(title="Get Lucky Summer (Beacon Isle) Plett – Prime Circle & Lee Cole (Edition 2)",category="concert",start_date="2026-12-27",time="15:00-21:00",town="Plettenberg Bay",venue="Beacon Isle Resort",venue_address="Beacon Island Crescent, Plettenberg Bay",price_from="R180",ticket_url="https://www.howler.co.za/GLSBI2",source_url="https://new-ux.howler.co.za/events/get-lucky-summer-beacon-isle-plett-ft-prime-circle-lee-cole-edition-2-1074",source_name=H,alt_sources=["https://www.howler.co.za/GLSBI2"],notes="Lawns at Beacon Island.")
add(title="Get Lucky Summer (Beacon Isle) Plett – Will Linley & friends (Edition 3)",category="concert",start_date="2027-01-03",time="",town="Plettenberg Bay",venue="Beacon Isle Resort",venue_address="Beacon Island Crescent, Plettenberg Bay",price_from="R180",ticket_url="https://www.howler.co.za/GLSBI3",source_url="https://www.howler.co.za/GLSBI3",source_name=H,alt_sources=[],notes="")
add(title="Get Lucky Summer Plett (Beacon Isle) – GoodLuck, Veranda Panda & Amy Tjasink (Edition 4)",category="concert",start_date="2027-01-10",time="",town="Plettenberg Bay",venue="Beacon Isle Resort",venue_address="Beacon Island Crescent, Plettenberg Bay",price_from="R180",ticket_url="https://www.howler.co.za/GLSBI4",source_url="https://www.howler.co.za/GLSBI4",source_name=H,alt_sources=["https://new-ux.howler.co.za/events/get-lucky-summer-plett-beacon-isle-goodluck-veranda-panda-amy-tjasink-edition-4-9d88"],notes="")
add(title="Plett NYE Festival – GoodLuck, The Parlotones, Booshle G & Saxby Twins (Get Lucky Summer NYE)",category="festival",start_date="2026-12-31",end_date="2027-01-01",time="Gates 17:00, music until 01:00",town="Plettenberg Bay",venue="Plett Rugby Club",price_from="R320",ticket_url="https://www.howler.co.za/GLSNYE26",source_url="https://www.howler.co.za/GLSNYE26",source_name=H,alt_sources=["https://www.plett-tourism.co.za/events/get-lucky-summer-nye-2026/"],notes="Under 18s must be accompanied by an adult.")
add(title="Get Lucky Summer Knysna – GoodLuck, The Parlotones, Booshle G, Veranda Panda & Lee Cole",category="concert",start_date="2026-12-29",time="15:00-21:30",town="Knysna",venue="Loerie Park Sports Grounds",venue_address="George Rex Drive, Knysna",price_from="R180",ticket_url="https://www.howler.co.za/glsknysna26",source_url="https://www.howler.co.za/events/get-lucky-summer-knsyna-ft-goodluck-the-parlotones-booshle-g-veranda-panda-lee-cole-72a0",source_name=H,alt_sources=["https://www.howler.co.za/glsknysna26"],notes="Kids U12 R180; family of 4 R280; early bird R300.")
add(title="Wanderbay NYE 2026 (Zakes Bantwini & more)",category="festival",start_date="2026-12-31",end_date="2027-01-01",time="17:00",town="Plettenberg Bay",venue="Cairnbrogie",venue_address="Plettenberg Bay Airport Road, Kranshoek, Plettenberg Bay",price_from="R575",ticket_url="https://www.howler.co.za/wanderbaynye2026",source_url="https://www.howler.co.za/wanderbaynye2026",source_name=H,alt_sources=["https://www.plett-tourism.co.za/events/wanderbay-nye-2026/","http://wanderbay.co.za/","https://festival101.co.za/events/wanderbay-nye-festival-2026-plettenberg-bay/"],notes="Electronic music (Afro house to disco), 18+.")
add(title="Wanderbay: Sexy Groovy Love showcase",category="festival",start_date="2026-12-28",time="",town="Plettenberg Bay",venue="Cairnbrogie",venue_address="Plettenberg Bay Airport Road, Kranshoek, Plettenberg Bay",price_from="",ticket_url="http://wanderbay.co.za/",source_url="http://wanderbay.co.za/",source_name="Wanderbay (official site)",alt_sources=[],notes="Season pass covers 28 Dec showcase and NYE.")
add(title="Wild Spirit Festival of Friends",category="festival",start_date="2026-12-28",end_date="2027-01-02",time="Gates 12:00-17:00 on 28 Dec",town="Nature's Valley",venue="Wild Spirit Lodge & Backpackers",venue_address="R102 Nature's Valley Road, The Crags",price_from="",ticket_url="https://www.wildspiritfestival.co.za/apply",source_url="https://www.wildspiritfestival.co.za/",source_name="Wild Spirit Festival (official site)",alt_sources=[OTR],notes="11th annual 5-day New Year camping festival: music, art, workshops. Line-up due Nov 2026.")

add(title="Bundu Bashers – psychedelic underground festival",category="festival",start_date="2026-12-30",end_date="2027-01-02",time="12:00 30 Dec – 19:00 2 Jan",town="Tsitsikamma",venue="Tannehof Guest farm",venue_address="Farm Rd, Bluelilliesbush, Tsitsikamma, 6308",price_from="R270",ticket_url="https://www.howler.co.za/BUNDUBASHERS",source_url="https://www.howler.co.za/BUNDUBASHERS",source_name="Howler",alt_sources=[],notes="Psytrance camping festival, 18+. Map pin is approximate (Tsitsikamma area, placed at Storms River).")
