# town -> (nominatim query, region, garden_route)
TOWNS={
 "George":("George, Western Cape","Garden Route",True),
 "Wilderness":("Wilderness, George, Western Cape","Garden Route",True),
 "Sedgefield":("Sedgefield, Western Cape","Garden Route",True),
 "Knysna":("Knysna, Western Cape","Garden Route",True),
 "Plettenberg Bay":("Plettenberg Bay, Western Cape","Garden Route",True),
 "The Crags":("The Crags, Bitou, Western Cape","Garden Route",True),
 "Nature's Valley":("Nature's Valley, Western Cape","Garden Route",True),
 "Storms River":("Storms River, Eastern Cape","Garden Route",True),
 "Tsitsikamma":("Storms River, Eastern Cape","Garden Route",True),
 "Mossel Bay":("Mossel Bay, Western Cape","Mossel Bay",True),
 "Hartenbos":("Hartenbos, Western Cape","Mossel Bay",True),
 "Groot Brak":("Great Brak River, Western Cape","Mossel Bay",True),
 "Herbertsdale":("Herbertsdale, Western Cape","Mossel Bay",True),
 "Klein Brak":("Klein Brakrivier, Western Cape","Mossel Bay",True),
 "Oudtshoorn":("Oudtshoorn, Western Cape","Garden Route",True),
 "Stilbaai":("Stilbaai, Western Cape","Hessequa (Stilbaai)",False),
 "Riversdale":("Riversdale, Western Cape","Hessequa (Stilbaai)",False),
 "Hermanus":("Hermanus, Western Cape","Overberg",False),
 "Kleinmond":("Kleinmond, Western Cape","Overberg",False),
 "Pringle Bay":("Pringle Bay, Western Cape","Overberg",False),
 "Stanford":("Stanford, Western Cape","Overberg",False),
 "Gansbaai":("Gansbaai, Western Cape","Overberg",False),
 "Struisbaai":("Struisbaai, Western Cape","Overberg",False),
 "L'Agulhas":("L'Agulhas, Western Cape","Overberg",False),
 "Somerset West":("Somerset West, Western Cape","Cape Town",False),
 "Cape Town":("Cape Town, Western Cape","Cape Town",False),
 "Jeffreys Bay":("Jeffreys Bay, Eastern Cape","Kouga/Jeffreys Bay",False),
 "St Francis Bay":("St Francis Bay, Eastern Cape","Kouga/Jeffreys Bay",False),
 "Humansdorp":("Humansdorp, Eastern Cape","Kouga/Jeffreys Bay",False),
}
